import { structureModel } from "../models/structure.model";

export const structure: structureModel = {
  sections: [
    {
      section_id: 0,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 2.1%%; left: 30%;",
              style_five: "",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 2.1%%; left: 35%",
              style_five: "",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 1.6%; left: 40%",
              style_five: "",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 1.6%; left: 45%",
              style_five: "",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 20%; left: 45%;",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 60.3%; left: 24.13%;",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 60.3%; left: 66.13%;",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 46%; left: 45.5%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 1,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 1,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 1.13%; right: 39.63%;",
              style_three: "top: 1.13%; right: 39.63%;",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            },
            {
              id: 2,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 2.5%; right: 34.63%;",
              style_three: "top: 1.13%; right: 39.63%;",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            },
            {
              id: 3,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 4.38%; right: 29.75% ;",
              style_three: "top: 1.13%; right: 39.63%;",
              style_four: "",
              style_five: "",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 1,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 5.5%; right: 27.75% ;",
              style_four: "top: 6.2%; right: 27.2%;",
              style_five: "top: 7.8%; right: 27.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 2,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 2.5%; right: 35.2%;",
              style_four: "top: 4%; right: 32.5%;",
              style_five: "top: 3.38%; right: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 3,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 1.5%; right: 42.4%",
              style_four: "top: 2.2%; right: 38.2%;",
              style_five: "top: 4.8%; right: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 4,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 1.5%; right: 42.4%",
              style_four: "top: 1.4%; right: 44%",
              style_five: "top: 1.3%; right: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 5,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "top: 3.13%; right: 44.63%",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 2.5%; right: 35.2%;",
              style_two: "top: 3.38%; right: 30.75%;",
              style_three: "top: 5.5%; right: 27.75% ;",
              style_four: "top: 6.2%; right: 27.2%;",
              style_five: "top: 7.8%; right: 27.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 1.3%; right: 39.63%;",
              style_three: "top: 2.5%; right: 35.2%;",
              style_four: "top: 4%; right: 32.5%;",
              style_five: "top: 3.38%; right: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 1.5%; right: 42.4%",
              style_four: "top: 2.2%; right: 38.2%;",
              style_five: "top: 4.8%; right: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 1.4%; right: 44%",
              style_five: "top: 1.3%; right: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "top: 3.13%; right: 44.63%",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 2.5%; right: 35.2%;",
              style_two: "top: 3.38%; right: 30.75%;",
              style_three: "top: 5.5%; right: 27.75% ;",
              style_four: "top: 6.2%; right: 27.2%;",
              style_five: "top: 7.8%; right: 27.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 1.3%; right: 39.63%;",
              style_three: "top: 2.5%; right: 35.2%;",
              style_four: "top: 4%; right: 32.5%;",
              style_five: "top: 3.38%; right: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 1.5%; right: 42.4%",
              style_four: "top: 2.2%; right: 38.2%;",
              style_five: "top: 4.8%; right: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "top: 1.4%; right: 44%",
              style_five: "top: 1.3%; right: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "top: 3.13%; right: 44.63%",
              color: "background-color: #193B94;"
            }
          ],
        }
      ]
    },
    {
      section_id: 2,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 31,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 11.25%; right: 18.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #94198E;"
            },
            {
              id: 32,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 14.75%; right: 14.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #94198E;"
            },
            {
              id: 33,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 18.75%; right: 10.75%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #94198E;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 20.7%; right: 10%",
              style_four: "top: 9.8%; right: 21.5%",
              style_five: "top: 22.8%; right: 10.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 15%; right: 14.5%;",
              style_four: "top: 13%; right: 17%;",
              style_five: "top: 17.7%; right: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 10%; right: 20%;",
              style_four: "top: 17%; right: 13%;",
              style_five: "top: 16%; right: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 22%; right: 10.2%;",
              style_five: "top: 11.1%; right: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "top: 10.7%; right: 23%",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 15%; right: 14.5%;",
              style_two: "top: 17.7%; right: 11.3%;",
              style_three: "top: 20.7%; right: 10%",
              style_four: "top: 9.8%; right: 21.5%",
              style_five: "top: 22.8%; right: 10.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 11.1%; right: 17.7%;",
              style_three: "top: 15%; right: 14.5%;",
              style_four: "top: 13%; right: 17%;",
              style_five: "top: 17.7%; right: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 10%; right: 20%;",
              style_four: "top: 17%; right: 13%;",
              style_five: "top: 16%; right: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "top: 22%; right: 10.2%;",
              style_five: "top: 11.1%; right: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "top: 10.7%; right: 23%",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 15%; right: 14.5%;",
              style_two: "top: 17.7%; right: 11.3%;",
              style_three: "top: 20.7%; right: 10%",
              style_four: "top: 9.8%; right: 21.5%",
              style_five: "top: 22.8%; right: 10.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 11.1%; right: 17.7%;",
              style_three: "top: 15%; right: 14.5%;",
              style_four: "top: 13%; right: 17%;",
              style_five: "top: 17.7%; right: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 10%; right: 20%;",
              style_four: "top: 17%; right: 13%;",
              style_five: "top: 16%; right: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "top: 22%; right: 10.2%;",
              style_five: "top: 11.1%; right: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "top: 10.7%; right: 23%",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 3,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 7,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 29.5%; right: 4.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #199434;"
            },
            {
              id: 8,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 34.5% ; right: 2.5%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #199434;"
            },
            {
              id: 9,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 39.63%; right: 1.13%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #199434;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 42.5%; right: 2%;",
              style_four: "top: 43.8%; right: 2.2%;",
              style_five: "top: 44.8%; right: 3.5%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 35%; right: 3%;",
              style_four: "top: 38.2%; right: 3%;",
              style_five: "top: 40.1%; right: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 28%; right: 5.5%",
              style_four: "top: 32.8%; right: 4.5%;",
              style_five: "top: 36.3%; right: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 27.8%; right: 6.5%",
              style_five: "top: 31.3%; right: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "top: 28%; right: 7.7%",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 35%; right: 3%;",
              style_two: "top: 40.1%; right: 1.1%;",
              style_three: "top: 42.5%; right: 2%;",
              style_four: "top: 43.8%; right: 2.2%;",
              style_five: "top: 44.8%; right: 3.5%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 31.3%; right: 3.63%;",
              style_three: "top: 35%; right: 3%;",
              style_four: "top: 38.2%; right: 3%;",
              style_five: "top: 40.1%; right: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 28%; right: 5.5%",
              style_four: "top: 32.8%; right: 4.5%;",
              style_five: "top: 36.3%; right: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "top: 27.8%; right: 6.5%",
              style_five: "top: 31.3%; right: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "top: 28%; right: 7.7%",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 35%; right: 3%;",
              style_two: "top: 40.1%; right: 1.1%;",
              style_three: "top: 42.5%; right: 2%;",
              style_four: "top: 43.8%; right: 2.2%;",
              style_five: "top: 44.8%; right: 3.5%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 31.3%; right: 3.63%;",
              style_three: "top: 35%; right: 3%;",
              style_four: "top: 38.2%; right: 3%;",
              style_five: "top: 40.1%; right: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 28%; right: 5.5%",
              style_four: "top: 32.8%; right: 4.5%;",
              style_five: "top: 36.3%; right: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "top: 27.8%; right: 6.5%",
              style_five: "top: 31.3%; right: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "top: 28%; right: 7.7%",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 4,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 10,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 39.63%; right: 1.13%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #941D19;"
            },
            {
              id: 11,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 34.5%; right: 2.5%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #941D19;"
            },
            {
              id: 12,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 29.5%; right: 4.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #941D19;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 28%; right: 5.5%",
              style_four: "bottom: 27.8%; right: 6.5%",
              style_five: "bottom: 28%; right: 7.7%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 35%; right: 3%;",
              style_four: "bottom: 32.8%; right: 4.5%;",
              style_five: "bottom: 31.3%; right: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 42.5%; right: 2%;",
              style_four: "bottom: 38.2%; right: 3%;",
              style_five: "bottom: 36.3%; right: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "bottom: 43.8%; right: 2.2%;",
              style_five: "bottom: 40.1%; right: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 44.8%; right: 3.5%",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 35%; right: 3%;",
              style_two: "bottom: 31.3%; right: 3.63%;",
              style_three: "bottom: 28%; right: 5.5%",
              style_four: "bottom: 27.8%; right: 6.5%",
              style_five: "bottom: 28%; right: 7.7%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 40.1%; right: 1.1%;",
              style_three: "bottom: 35%; right: 3%;",
              style_four: "bottom: 32.8%; right: 4.5%;",
              style_five: "bottom: 31.3%; right: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 42.5%; right: 2%;",
              style_four: "bottom: 38.2%; right: 3%;",
              style_five: "bottom: 36.3%; right: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 43.8%; right: 2.2%;",
              style_five: "bottom: 40.1%; right: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 44.8%; right: 3.5%",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 35%; right: 3%;",
              style_two: "bottom: 31.3%; right: 3.63%;",
              style_three: "bottom: 28%; right: 5.5%",
              style_four: "bottom: 27.8%; right: 6.5%",
              style_five: "bottom: 28%; right: 7.7%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 40.1%; right: 1.1%;",
              style_three: "bottom: 35%; right: 3%;",
              style_four: "bottom: 32.8%; right: 4.5%;",
              style_five: "bottom: 31.3%; right: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 42.5%; right: 2%;",
              style_four: "bottom: 38.2%; right: 3%;",
              style_five: "bottom: 36.3%; right: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 43.8%; right: 2.2%;",
              style_five: "bottom: 40.1%; right: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 44.8%; right: 3.5%",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 5,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 13,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 18.75%; right: 10.75%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #944E19;"
            },
            {
              id: 14,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 14.75%; right: 14.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #944E19;"
            },
            {
              id: 15,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 11.25%; right: 18.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #944E19;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 10%; right: 20%;",
              style_four: "bottom: 9.8%; right: 21.5%",
              style_five: "bottom: 10.7%; right: 23%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 15%; right: 14.5%;",
              style_four: "bottom: 13%; right: 17%;",
              style_five: "bottom: 11.1%; right: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 20.7%; right: 10%",
              style_four: "bottom: 17%; right: 13%;",
              style_five: "bottom: 16%; right: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "bottom: 22%; right: 10.2%;",
              style_five: "bottom: 17.7%; right: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 22.8%; right: 10.8%;",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 15%; right: 14.5%;",
              style_two: "bottom: 11.1%; right: 17.7%;",
              style_three: "bottom: 10%; right: 20%;",
              style_four: "bottom: 9.8%; right: 21.5%",
              style_five: "bottom: 10.7%; right: 23",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 17.7%; right: 11.3%;",
              style_three: "bottom: 15%; right: 14.5%;",
              style_four: "bottom: 13%; right: 17%;",
              style_five: "bottom: 11.1%; right: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 20.7%; right: 10%",
              style_four: "bottom: 17%; right: 13%;",
              style_five: "bottom: 16%; right: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 22%; right: 10.2%;",
              style_five: "bottom: 17.7%; right: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 22.8%; right: 10.8%;",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 15%; right: 14.5%;",
              style_two: "bottom: 11.1%; right: 17.7%;",
              style_three: "bottom: 10%; right: 20%;",
              style_four: "bottom: 9.8%; right: 21.5%",
              style_five: "bottom: 10.7%; right: 23%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 17.7%; right: 11.3%;",
              style_three: "bottom: 15%; right: 14.5%;",
              style_four: "bottom: 13%; right: 17%;",
              style_five: "bottom: 11.1%; right: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 20.7%; right: 10%",
              style_four: "bottom: 17%; right: 13%;",
              style_five: "bottom: 16%; right: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 22%; right: 10.2%;",
              style_five: "bottom: 17.7%; right: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 22.8%; right: 10.8%;",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 6,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 16,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 4.38%; right: 29.75% ;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #659419;"
            },
            {
              id: 17,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 2.5%; right: 34.63%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #659419;"
            },
            {
              id: 18,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 1.13%; right: 39.63%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #659419;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 1.5%; right: 42.4%",
              style_four: "bottom: 1.4%; right: 44%",
              style_five: "bottom: 3.13%; right: 44.63%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 2.9%; right: 34.8%;",
              style_four: "bottom: 2.2%; right: 38.2%;",
              style_five: "bottom: 1.3%; right: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 5.5%; right: 27.75%;",
              style_four: "bottom: 4%; right: 32.5%;",
              style_five: "bottom: 4.8%; right: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "bottom: 6.2%; right: 27.2%;",
              style_five: "bottom: 3.38%; right: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 7.8%; right: 27.8%;",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 2.9%; right: 34.8%;",
              style_two: "bottom: 1.3%; right: 39.63%;",
              style_three: "bottom: 1.5%; right: 42.4%",
              style_four: "bottom: 1.4%; right: 44%",
              style_five: "bottom: 3.13%; right: 44.63%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 3.38%; right: 30.75%;",
              style_three: "bottom: 2.9%; right: 34.8%;",
              style_four: "bottom: 2.2%; right: 38.2%;",
              style_five: "bottom: 1.3%; right: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 5.5%; right: 27.75%;",
              style_four: "bottom: 4%; right: 32.5%;",
              style_five: "bottom: 4.8%; right: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 6.2%; right: 27.2%;",
              style_five: "bottom: 3.38%; right: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 7.8%; right: 27.8%;",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 2.9%; right: 34.8%;",
              style_two: "bottom: 1.3%; right: 39.63%;",
              style_three: "bottom: 1.5%; right: 42.4%",
              style_four: "bottom: 1.4%; right: 44%",
              style_five: "bottom: 3.13%; right: 44.63%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 3.38%; right: 30.75%;",
              style_three: "bottom: 2.9%; right: 34.8%;",
              style_four: "bottom: 2.2%; right: 38.2%;",
              style_five: "bottom: 1.3%; right: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 5.5%; right: 27.75%;",
              style_four: "bottom: 4%; right: 32.5%;",
              style_five: "bottom: 4.8%; right: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 6.2%; right: 27.2%;",
              style_five: "bottom: 3.38%; right: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 7.8%; right: 27.8%;",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 7,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 19,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 1.13%; left: 39.63%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #6276AB;"
            },
            {
              id: 20,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 2.5%; left: 34.63%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #6276AB;"
            },
            {
              id: 21,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 4.38%; left: 29.75% ;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #6276AB;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 5.5%; left: 27.75% ;",
              style_four: "bottom: 6.2%; left: 27.2%;",
              style_five: "bottom: 7.8%; left: 27.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 2.9%; left: 34.8%;",
              style_four: "bottom: 4%; left: 32.5%;",
              style_five: "bottom: 3.38%; left: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 1.5%; left: 42.4%",
              style_four: "bottom: 2.2%; left: 38.2%;",
              style_five: "bottom: 4.8%; left: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "bottom: 1.4%; left: 44%",
              style_five: "bottom: 1.3%; left: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 3.13%; left: 44.63%",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 2.9%; left: 34.8%;",
              style_two: "bottom: 3.38%; left: 30.75%;",
              style_three: "bottom: 5.5%; left: 27.75% ;",
              style_four: "bottom: 6.2%; left: 27.2%;",
              style_five: "bottom: 7.8%; left: 27.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 1.3%; left: 39.63%;",
              style_three: "bottom: 2.9%; left: 34.8%;",
              style_four: "bottom: 4%; left: 32.5%;",
              style_five: "bottom: 3.38%; left: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 1.5%; left: 42.4%",
              style_four: "bottom: 2.2%; left: 38.2%;",
              style_five: "bottom: 4.8%; left: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 1.4%; left: 44%",
              style_five: "bottom: 1.3%; left: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 3.13%; left: 44.63%",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 2.9%; left: 34.8%;",
              style_two: "bottom: 3.38%; left: 30.75%;",
              style_three: "bottom: 5.5%; left: 27.75% ;",
              style_four: "bottom: 6.2%; left: 27.2%;",
              style_five: "bottom: 7.8%; left: 27.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 1.3%; left: 39.63%;",
              style_three: "bottom: 2.9%; left: 34.8%;",
              style_four: "bottom: 4%; left: 32.5%;",
              style_five: "bottom: 3.38%; left: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 1.5%; left: 42.4%",
              style_four: "bottom: 2.2%; left: 38.2%;",
              style_five: "bottom: 4.8%; left: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 1.4%; left: 44%",
              style_five: "bottom: 1.3%; left: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 3.13%; left: 44.63%",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 8,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 22,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 11.25%; left: 18.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #83FFFB;"
            },
            {
              id: 23,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 14.75%; left: 14.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #83FFFB;"
            },
            {
              id: 24,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 18.75%; left: 10.75%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #83FFFB;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 20.7%; left: 10%;",
              style_four: "bottom: 22%; left: 10.2%;",
              style_five: "bottom: 22.8%; left: 10.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 15%; left: 14.5%;",
              style_four: "bottom: 17%; left: 13%;",
              style_five: "bottom: 17.7%; left: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 10%; left: 20%",
              style_four: "bottom: 13%; left: 17%;",
              style_five: "bottom: 16%; left: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "bottom: 9.8%; left: 21.5%",
              style_five: "bottom: 11.1%; left: 17.7%",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 10.7%; left: 23%",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 15%; left: 14.5%;",
              style_two: "bottom: 17.7%; left: 11.3%;",
              style_three: "bottom: 20.7%; left: 10%;",
              style_four: "bottom: 22%; left: 10.2%;",
              style_five: "bottom: 22.8%; left: 10.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 11.1%; left: 17.7%;",
              style_three: "bottom: 15%; left: 14.5%;",
              style_four: "bottom: 17%; left: 13%;",
              style_five: "bottom: 17.7%; left: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 10%; left: 20%",
              style_four: "bottom: 13%; left: 17%;",
              style_five: "bottom: 16%; left: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 9.8%; left: 21.5%",
              style_five: "bottom: 11.1%; left: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 10.7%; left: 23%",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 15%; left: 14.5%;",
              style_two: "bottom: 17.7%; left: 11.3%;",
              style_three: "bottom: 20.7%; left: 10%;",
              style_four: "bottom: 22%; left: 10.2%;",
              style_five: "bottom: 22.8%; left: 10.8%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 11.1%; left: 17.7%;",
              style_three: "bottom: 15%; left: 14.5%;",
              style_four: "bottom: 13%; left: 17%;",
              style_five: "bottom: 16%; left: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 10%; left: 20%",
              style_four: "bottom: 13%; left: 17%;",
              style_five: "bottom: 16%; left: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 9.8%; left: 21.5%",
              style_five: "bottom: 11.1%; left: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 10.7%; left: 23%",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 9,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 25,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 29.5%; left: 4.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #6276AB;"
            },
            {
              id: 26,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 34.5%; left: 2.5%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #6276AB;"
            },
            {
              id: 27,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "bottom: 39.63%; left: 1.13%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #6276AB;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 42.5%; left: 2%;",
              style_four: "bottom: 43.8%; left: 2.2%;",
              style_five: "bottom: 44.8%; left: 3.5%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 35%; left: 3%;",
              style_four: "bottom: 38.2%; left: 3%;",
              style_five: "bottom: 40.1%; left: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "bottom: 28%; left: 5.5%;",
              style_four: "bottom: 32.8%; left: 4.5%;",
              style_five: "bottom: 36.3%; left: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "bottom: 27.8%; left: 6.5%",
              style_five: "bottom: 31.3%; left: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 28%; left: 7.7%",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 35%; left: 3%;",
              style_two: "bottom: 40.1%; left: 1.1%;",
              style_three: "bottom: 42.5%; left: 2%;",
              style_four: "bottom: 43.8%; left: 2.2%;",
              style_five: "bottom: 44.8%; left: 3.5%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 31.3%; left: 3.63%;",
              style_three: "bottom: 35%; left: 3%;",
              style_four: "bottom: 38.2%; left: 3%;",
              style_five: "bottom: 40.1%; left: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 28%; left: 5.5%",
              style_four: "bottom: 32.8%; left: 4.5%;",
              style_five: "bottom: 36.3%; left: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 27.8%; left: 6.5%",
              style_five: "bottom: 31.3%; left: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 28%; left: 7.7%",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "bottom: 35%; left: 3%;",
              style_two: "bottom: 40.1%; left: 1.1%;",
              style_three: "bottom: 42.5%; left: 2%;",
              style_four: "bottom: 43.8%; left: 2.2%;",
              style_five: "bottom: 44.8%; left: 3.5%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "bottom: 31.3%; left: 3.63%;",
              style_three: "bottom: 35%; left: 3%;",
              style_four: "bottom: 38.2%; left: 3%;",
              style_five: "bottom: 40.1%; left: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "bottom: 28%; left: 5.5%",
              style_four: "bottom: 32.8%; left: 4.5%;",
              style_five: "bottom: 36.3%; left: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "bottom: 27.8%; left: 6.5%",
              style_five: "bottom: 31.3%; left: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "bottom: 28%; left: 7.7%",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 10,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 28,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 39.63%; left: 1.13%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #00A8DB;"
            },
            {
              id: 29,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 34.5%; left: 2.5%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #00A8DB;"
            },
            {
              id: 30,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 29.5%; left: 4.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #00A8DB;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 28%; left: 5.5%",
              style_four: "top: 27.8%; left: 6.5%",
              style_five: "top: 28%; left: 7.7%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 35%; left: 3%;",
              style_four: "top: 32.8%; left: 4.5%;",
              style_five: "top: 31.3%; left: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 42.5%; left: 2%;",
              style_four: "top: 38.2%; left: 3%;",
              style_five: "top: 36.3%; left: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 43.8%; left: 2.2%;",
              style_five: "top: 40.1%; left: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "top: 44.8%; left: 3.5%",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 35%; left: 3%;",
              style_two: "top: 31.3%; left: 3.63%;",
              style_three: "top: 28%; left: 5.5%",
              style_four: "top: 27.8%; left: 6.5%",
              style_five: "top: 28%; left: 7.7%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 40.1%; left: 1.1%;",
              style_three: "top: 35%; left: 3%;",
              style_four: "top: 32.8%; left: 4.5%;",
              style_five: "top: 31.3%; left: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 42.5%; left: 2%;",
              style_four: "top: 38.2%; left: 3%;",
              style_five: "top: 36.3%; left: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 43.8%; left: 2.2%;",
              style_five: "top: 40.1%; left: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "top: 44.8%; left: 3.5%",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 35%; left: 3%;",
              style_two: "top: 31.3%; left: 3.63%;",
              style_three: "top: 28%; left: 5.5%",
              style_four: "top: 27.8%; left: 6.5%",
              style_five: "top: 28%; left: 7.7%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 40.1%; left: 1.1%;",
              style_three: "top: 35%; left: 3%;",
              style_four: "top: 32.8%; left: 4.5%;",
              style_five: "top: 31.3%; left: 3.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 42.5%; left: 2%;",
              style_four: "top: 38.2%; left: 3%;",
              style_five: "top: 36.3%; left: 4.95%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "top: 43.8%; left: 2.2%;",
              style_five: "top: 40.1%; left: 1.1%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "top: 44.8%; left: 3.5%",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 11,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 31,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 18.75%; left: 10.75%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #093F4F;"
            },
            {
              id: 32,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 14.75%; left: 14.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #093F4F;"
            },
            {
              id: 33,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 11.25%; left: 18.25%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #093F4F;"

            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 10%; left: 20%",
              style_four: "top: 9.8%; left: 21.5%",
              style_five: "top: 10.7%; left: 23%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 15%; left: 14.5%;",
              style_four: "top: 13%; left: 17%;",
              style_five: "top: 11.1%; left: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 20.7%; left: 10%;",
              style_four: "top: 17%; left: 13%;",
              style_five: "top: 16%; left: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 22%; left: 10.2%;",
              style_five: "top: 17.7%; left: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "top: 22.8%; left: 10.8%;",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 15%; left: 14.5%;",
              style_two: "top: 11.1%; left: 17.7%;",
              style_three: "top: 10%; left: 20%",
              style_four: "top: 9.8%; left: 21.5%",
              style_five: "top: 10.7%; left: 23%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 17.7%; left: 11.3%;",
              style_three: "top: 15%; left: 14.5%;",
              style_four: "top: 13%; left: 17%;",
              style_five: "top: 11.1%; left: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 20.7%; left: 10%;",
              style_four: "top: 17%; left: 13%;",
              style_five: "top: 16%; left: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "top: 22%; left: 10.2%;",
              style_five: "top: 17.7%; left: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "top: 22.8%; left: 10.8%",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 15%; left: 14.5%;",
              style_two: "top: 11.1%; left: 17.7%;",
              style_three: "top: 10%; left: 20%",
              style_four: "top: 9.8%; left: 21.5%",
              style_five: "top: 10.7%; left: 23%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 17.7%; left: 11.3%;",
              style_three: "top: 15%; left: 14.5%;",
              style_four: "top: 13%; left: 17%;",
              style_five: "top: 11.1%; left: 17.7%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 20.7%; left: 10%;",
              style_four: "top: 17%; left: 13%;",
              style_five: "top: 16%; left: 16.2%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "top: 22%; left: 10.2%;",
              style_five: "top: 17.7%; left: 11.3%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "top: 22.8%; left: 10.8%;",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
    {
      section_id: 12,
      level_depth: [
        {
          id: 0,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 4.38%; left: 29.75% ;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #6276AB;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 2.5%; left: 34.63%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #6276AB;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "top: 1.13%; left: 39.63%;",
              style_three: "",
              style_four: "",
              style_five: "",
              color: "background-color: #6276AB;"
            },
          ],
        },
        {
          id: 1,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 1.5%; left: 42.4%",
              style_four: "top: 1.4%; left: 44%",
              style_five: "top: 3.13%; left: 44.63%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 2.5%; left: 35.2%;",
              style_four: "top: 2.2%; left: 38.2%;",
              style_five: "top: 1.3%; left: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "top: 5.5%; left: 27.75% ;",
              style_four: "top: 4%; left: 32.5%;",
              style_five: "top: 4.8%; left: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 6.2%; left: 27.2%;",
              style_five: "top: 3.38%; left: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "top: 7.8%; left: 27.8%;",
              color: "background-color: #193B94;"
            }
          ],
        },
        {
          id: 2,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 2.5%; left: 35.2%;",
              style_two: "top: 1.3%; left: 39.63%;",
              style_three: "top: 1.5%; left: 42.4%",
              style_four: "top: 1.4%; left: 44%",
              style_five: "top: 3.13%; left: 44.63%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 3.38%; left: 30.75%;",
              style_three: "top: 2.5%; left: 35.2%;",
              style_four: "top: 2.2%; left: 38.2%;",
              style_five: "top: 1.3%; left: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 5.5%; left: 27.75% ;",
              style_four: "top: 4%; left: 32.5%;",
              style_five: "top: 4.8%; left: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "top: 6.2%; left: 27.2%;",
              style_five: "top: 3.38%; left: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_three: "",
              style_four: "",
              style_five: "top: 7.8%; left: 27.8%;",
              color: "background-color: #193B94;"
            },
          ],
        },
        {
          id: 3,
          count: 0,
          spells: [
            {
              id: 34,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "top: 2.5%; left: 35.2%;",
              style_two: "top: 1.3%; left: 39.63%;",
              style_three: "top: 1.5%; left: 42.4%",
              style_four: "top: 1.4%; left: 44%",
              style_five: "top: 3.13%; left: 44.63%",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "top: 3.38%; left: 30.75%;",
              style_three: "top: 2.5%; left: 35.2%;",
              style_four: "top: 2.2%; left: 38.2%;",
              style_five: "top: 1.3%; left: 39.63%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "top: 5.5%; left: 27.75% ;",
              style_four: "top: 4%; left: 32.5%;",
              style_five: "top: 4.8%; left: 35.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 35,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "top: 6.2%; left: 27.2%;",
              style_five: "top: 3.38%; left: 30.75%;",
              color: "background-color: #193B94;"
            },
            {
              id: 36,
              spell_id: "",
              name: "",
              description: "",
              image: "",
              style: "",
              style_one: "",
              style_two: "",
              style_three: "",
              style_four: "",
              style_five: "top: 7.8%; left: 27.8%;",
              color: "background-color: #193B94;"
            },
          ],
        }
      ]
    },
  ]
}
