notifications:
  email:
    recipients:
      -

language: node_js

node_js:
  - 16

before_script:
  - npm install

script:
  - npm run test:headless

before_deploy:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $token
  local_dir: dist/SkillWheel
  on:
    branch: main
